# Imports

In [0]:
%matplotlib inline
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix

import math

# Downloading Data

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
data = input_data.read_data_sets('data/MNIST/', one_hot = True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting data/MNIST/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting data/MNIST/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting data/MNIST/t10k-images-idx3-ubyte.gz
Extracting data/MNIST/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


# Exploring Dataset

In [3]:
data.test.images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [4]:
print("Size of:")
print("- Training-set:\t\t{}".format(len(data.train.labels)))
print("- Validation-set:\t{}".format(len(data.validation.labels)))
print("- Test-set:\t\t{}".format(len(data.test.labels)))

Size of:
- Training-set:		55000
- Validation-set:	5000
- Test-set:		10000


In [5]:
data.test.labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
data.test.labels[0:5, :] #one hot encoded dependent variable (row wise, one row one number)

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [0]:
data.test.cls = np.array([label.argmax() for label in data.test.labels])

In [9]:
data.test.cls[0:5] #Actul class in dependent variableZ

array([7, 2, 1, 0, 4])

# Data Dimensions variables

In [0]:
img_size = 28 #images are 28 Pixels in each direction

In [0]:
img_size_flat = img_size * img_size #images are stored in one dimensional array of this length

In [0]:
img_shape = (img_size, img_size)

In [0]:
num_classes = 10

# Placeholders and Varaibles

In [0]:
X = tf.placeholder(tf.float32, [None, img_size_flat]) 
#placeholder in tensorflow hold the input data
#[None, img_size_flat] means it is a 2-d Tensor....None means there can be arbitrary number of rows....no of columns  = img_size_flat for each row

In [0]:
y_cls = tf.placeholder(tf.int64, [None])      #normal interger classes

In [0]:
W = tf.Variable(tf.zeros([img_size_flat, num_classes])) #weights
#Variable are all the things we want tensorflow to find for us

In [0]:
b = tf.Variable(tf.zeros([num_classes])) #biases

In [0]:
init = tf.global_variables_initializer()

# Simple Neural Network (Model)

In [0]:
y_pred = tf.nn.softmax(tf.matmul(X, W)+b)    #predicted probabilities 10 values per label

In [0]:
y_ = tf.placeholder(tf.float32, [None, 10])  #actual one-hot encoded labels

In [0]:
y_pred_cls = tf.argmax(y_pred, axis = 1)

# Loss

In [0]:
cross_entropy = -tf.reduce_sum(y_*tf.log(y_pred))

# Accuracy

In [0]:
is_correct = tf.equal(tf.argmax(y_pred, 1), tf.argmax(y_, 1))

In [0]:
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Gradient

In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.003) #0.003 is learning rate

In [0]:
train_step = optimizer.minimize(cross_entropy)

# Starting Tensorflow Session

In [0]:
sess = tf.Session()

In [0]:
sess.run(init)

# Training Loop

In [0]:
for i in range(10000):
  
  #loading batch of images and labels
  batch_X, batch_y = data.train.next_batch(100)
  train_data = {X: batch_X, y_ : batch_y}
  
  #training
  sess.run(train_step, feed_dict = train_data)  #train step is the step that computed gradients
  
  #success on training data
  train_accuracy, train_cross_entropy = sess.run([accuracy, cross_entropy], feed_dict = train_data)
  
  #success on test data
test_data = {X: data.test.images, y_: data.test.labels}
test_accuracy, test_cross_entropy = sess.run([accuracy, cross_entropy], feed_dict = test_data)
  

In [36]:
test_accuracy

0.9245

**Helper Function to show performance**

In [0]:
def print_accuracy():
  acc = sess.run(accuracy, feed_dict = test_data)
  
  print('Accuracy on test-set : {0: .1%}'.format(acc))

In [38]:
print_accuracy()

Accuracy on test-set :  92.4%
